<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>bbcode</string>
    </array>
    <key>name</key>
    <string>BBCode</string>
    <key>scopeName</key>
    <string>text.bbcode</string>
    <key>foldingStartMarker</key>
    <string>\[[a-z][^\]]*\]</string>
    <key>foldingStopMarker</key>
    <string>\[/[^\]]+\]</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>begin</key>
        <string>^</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>meta.paragraph.bbcode</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#blocks</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#spans</string>
          </dict>
        </array>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>blocks</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_header</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_code</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block_quote</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_ul</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_ol</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#list_li</string>
          </dict>
        </array>
      </dict>
      <key>spans</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#span_bold</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#span_italic</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#span_url</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#span_unknown</string>
          </dict>
        </array>
      </dict>
      <key>span_url</key>
      <dict>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[(url)(=)([^\]]*)\])</string>
        <key>end</key>
        <string>(?i:(?&lt;!\\)\[/(\1)\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.link.begin.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.link.bbcode</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.link.bbcode</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>meta.url.bbcode</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.link.end.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.link.bbcode</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#spans</string>
          </dict>
        </array>
      </dict>
      <key>block_header</key>
      <dict>
        <key>name</key>
        <string>markup.heading.bbcode</string>
        <key>contentName</key>
        <string>entity.name.section.head.bbcode</string>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[(h\d+)\])</string>
        <key>end</key>
        <string>(?i:(?&lt;!\\)\[/(\1)\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.header.begin.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.header.bbcode</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.header.end.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.header.bbcode</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#spans</string>
          </dict>
        </array>
      </dict>
      <key>span_bold</key>
      <dict>
        <key>name</key>
        <string>markup.bold.bbcode</string>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[(b)\])</string>
        <key>end</key>
        <string>(?i:(?&lt;!\\)\[/(\1)\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.bold.begin.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.bold.bbcode</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.bold.end.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.bold.bbcode</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#spans</string>
          </dict>
        </array>
      </dict>
      <key>span_italic</key>
      <dict>
        <key>name</key>
        <string>markup.italic.bbcode</string>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[(i)\])</string>
        <key>end</key>
        <string>(?i:(?&lt;!\\)\[/(\1)\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.italic.begin.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.italic.bbcode</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.italic.end.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.italic.bbcode</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#spans</string>
          </dict>
        </array>
      </dict>
      <key>list_ol</key>
      <dict>
        <key>name</key>
        <string>markup.list.numbered.bbcode</string>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[(ol)\])</string>
        <key>end</key>
        <string>(?i:(?&lt;!\\)\[/(\1)\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.list.numbered.begin.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.list.numbered.bbcode</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.list.numbered.end.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.list.numbered.bbcode</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#list_li</string>
          </dict>
        </array>
      </dict>
      <key>list_ul</key>
      <dict>
        <key>name</key>
        <string>markup.list.unnumbered.bbcode</string>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[(ul)\])</string>
        <key>end</key>
        <string>(?i:(?&lt;!\\)\[/(\1)\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.list.unnumbered.begin.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.list.unnumbered.bbcode</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.list.unnumbered.end.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.list.unnumbered.bbcode</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#list_li</string>
          </dict>
        </array>
      </dict>
      <key>list_li</key>
      <dict>
        <key>name</key>
        <string>meta.paragraph.list.bbcode</string>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[(\*)\])</string>
        <key>end</key>
        <string>$</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.list-item.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.list-item.bbcode</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#spans</string>
          </dict>
        </array>
      </dict>
      <key>block_code</key>
      <dict>
        <key>name</key>
        <string>markup.raw.block.bbcode</string>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[(code)\])</string>
        <key>end</key>
        <string>(?i:(?&lt;!\\)\[/(\1)\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.raw.block.begin.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.raw.block.bbcode</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.raw.block.end.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.raw.block.bbcode</string>
          </dict>
        </dict>
      </dict>
      <key>block_quote</key>
      <dict>
        <key>name</key>
        <string>markup.quote.block.bbcode</string>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[(quote)(?:(=)([^\]]*))?\])</string>
        <key>end</key>
        <string>(?i:(?&lt;!\\)\[/(\1)\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.quote.block.begin.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.quote.block.bbcode</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.user.quoted.bbcode</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.user.quoted.bbcode</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.quote.block.end.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.quote.block.bbcode</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#blocks</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#spans</string>
          </dict>
        </array>
      </dict>
      <key>span_unknown</key>
      <dict>
        <key>name</key>
        <string>meta.unknown-tag.bbcode</string>
        <key>begin</key>
        <string>(?i:(?&lt;!\\)\[([^\]]+)\])</string>
        <key>end</key>
        <string>(?i:(?&lt;!\\)\[/(\1)\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.unknown.begin.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.unknown.bbcode</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.tag.unknown.end.bbcode</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.tag.unknown.bbcode</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#blocks</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#spans</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>