<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Cowlips</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#source</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#loop0</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>binnum_literal</key>
		<dict>
			<key>match</key>
			<string>#b[01]+\b</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.cowlips</string>
		</dict>
		<key>double_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.double.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.double.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x[a-fA-F0-9]{2}|X[a-fA-F0-9]{4}|[0-7]{2}|"|[a-z0])</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<key>empty_list_literal</key>
		<dict>
			<key>match</key>
			<string>'\(\s*\)</string>
			<key>name</key>
			<string>constant.language.empty-list.cowlips</string>
		</dict>
		<key>false_literal</key>
		<dict>
			<key>match</key>
			<string>#f\b</string>
			<key>name</key>
			<string>constant.language.false.cowlips</string>
		</dict>
		<key>float_num</key>
		<dict>
			<key>match</key>
			<string>\d+\.\d+([eE][+\-]?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.float.cowlips</string>
		</dict>
		<key>hexnum_literal</key>
		<dict>
			<key>match</key>
			<string>#x[a-fA-F0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.cowlips</string>
		</dict>
		<key>integer_num</key>
		<dict>
			<key>match</key>
			<string>\d+([eE][+\-]?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.integer.cowlips</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((?&lt;=\s|\()[\+\-/\*](?=\s|\()|\b(pow|remainder|modulo|integer-divide|round|integer-round|ceil|floor)\b)</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.cowlips</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s|\()[&gt;&lt;]=?(?=\s|\()|\b(eq|\bne)\b</string>
					<key>name</key>
					<string>keyword.operator.comparison.cowlips</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|or|not)\b</string>
					<key>name</key>
					<string>keyword.operator.logical.cowlips</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bitwise-(or|and|xor|shift)|arithmetic-shift)\b</string>
					<key>name</key>
					<string>keyword.operator.bitwise.cowlips</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\blet\b</string>
					<key>name</key>
					<string>keyword.control.let.cowlips</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bloop\b</string>
					<key>name</key>
					<string>keyword.control.loop.cowlips</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bbegin\b</string>
					<key>name</key>
					<string>keyword.control.begin.cowlips</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bcase\b</string>
					<key>name</key>
					<string>keyword.control.case.cowlips</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bif\b</string>
					<key>name</key>
					<string>keyword.control.if.cowlips</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.define.cowlips</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.define.cowlips</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(define)\s+([a-zA-Z_+=\-!@#\$%\^&amp;*\.&lt;&gt;?:|\\/][a-zA-Z0-9_+=\-!@#\$%\^&amp;*\.&lt;&gt;?:|\\/]*)</string>
					<key>name</key>
					<string>meta.expr.define.cowlips</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(define)\s*(\()([a-zA-Z_+=\-!@#\$%\^&amp;*\.&lt;&gt;?:|\\/][a-zA-Z0-9_+=\-!@#\$%\^&amp;*\.&lt;&gt;?:|\\/]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.define.cowlips</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.begin.expr.cowlips</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.cowlips</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.end.expr.cowlips</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.expr.define.function.cowlips</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z_+=\-!@#\$%\^&amp;*\.&lt;&gt;?:|\\/][a-zA-Z0-9_+=\-!@#\$%\^&amp;*\.&lt;&gt;?:|\\/]*</string>
							<key>name</key>
							<string>variable.parameter.function.cowlips</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>let_expr</key>
		<dict>
			<key>begin</key>
			<string>\b(let)\s*(?=\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.let.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>name</key>
			<string>meta.expr.let.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#loop15</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#float_num</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer_num</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#empty_list_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#true_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#false_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#null_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#hexnum_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#octnum_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#binnum_literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>loop0</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop0.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop0.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop0.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop1</string>
				</dict>
			</array>
		</dict>
		<key>loop1</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop1.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop1.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop1.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop2</string>
				</dict>
			</array>
		</dict>
		<key>loop10</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop10.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop10.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop10.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop11</string>
				</dict>
			</array>
		</dict>
		<key>loop11</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop11.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop11.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop11.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop12</string>
				</dict>
			</array>
		</dict>
		<key>loop12</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop12.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop12.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop12.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop13</string>
				</dict>
			</array>
		</dict>
		<key>loop13</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop13.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop13.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop13.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop14</string>
				</dict>
			</array>
		</dict>
		<key>loop14</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop14.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop14.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop14.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop15</string>
				</dict>
			</array>
		</dict>
		<key>loop15</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop15.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop15.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop15.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop0</string>
				</dict>
			</array>
		</dict>
		<key>loop2</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop2.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop2.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop2.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop3</string>
				</dict>
			</array>
		</dict>
		<key>loop3</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop3.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop3.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop3.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop4</string>
				</dict>
			</array>
		</dict>
		<key>loop4</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop4.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop4.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop4.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop5</string>
				</dict>
			</array>
		</dict>
		<key>loop5</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop5.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop5.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop5.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop6</string>
				</dict>
			</array>
		</dict>
		<key>loop6</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop6.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop6.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop6.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop7</string>
				</dict>
			</array>
		</dict>
		<key>loop7</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop7.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop7.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop7.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop8</string>
				</dict>
			</array>
		</dict>
		<key>loop8</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop8.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop8.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop8.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop9</string>
				</dict>
			</array>
		</dict>
		<key>loop9</key>
		<dict>
			<key>begin</key>
			<string>(?!&lt;=')\((?!=\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.begin.expr.loop9.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.end.expr.loop9.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.expr.loop9.cowlips</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop_guts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loop10</string>
				</dict>
			</array>
		</dict>
		<key>loop_guts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
			</array>
		</dict>
		<key>null_literal</key>
		<dict>
			<key>match</key>
			<string>#nil\b</string>
			<key>name</key>
			<string>constant.language.nil.cowlips</string>
		</dict>
		<key>octnum_literal</key>
		<dict>
			<key>match</key>
			<string>#o[0-7]+\b</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.cowlips</string>
		</dict>
		<key>quote</key>
		<dict>
			<key>match</key>
			<string>'</string>
			<key>name</key>
			<string>punctuation.section.quoted.cowlips</string>
		</dict>
		<key>raw_string</key>
		<dict>
			<key>begin</key>
			<string>(raw)(")([^\{]+)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.delimiter.string.raw.cowlips</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.double.cowlips</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.delimiter.string.separator.raw.cowlips</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.delimiter.string.separator.raw.cowlips</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})(\3)(\2)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.double.cowlips</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.delimiter.string.separator.raw.cowlips</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.delimiter.string.separator.raw.cowlips</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.raw.cowlips</string>
		</dict>
		<key>source</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quote</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#raw_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double_string</string>
				</dict>
			</array>
		</dict>
		<key>true_literal</key>
		<dict>
			<key>match</key>
			<string>#t\b</string>
			<key>name</key>
			<string>constant.language.true.cowlips</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.untitled</string>
	<key>uuid</key>
	<string>042C602C-40A7-40FC-8C8D-41AD6E295FBC</string>
</dict>
</plist>
